version: "3.8"

services:
  backend:
    image: myproject.azurecr.io/server:latest
    container_name: petjoy_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://petjoy-mysql.mysql.database.azure.com:3306/pet_joy_db?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: petjoy_user@petjoy-mysql
      SPRING_DATASOURCE_PASSWORD: Parola123!

  frontend:
    image: myproject.azurecr.io/client:latest
    container_name: petjoy_frontend
    restart: always
    ports:
      - "80:80"
