services:
  db:
    image: mysql:8.0
    container_name: petjoy_db
    restart: always
    environment:
      MYSQL_DATABASE: pet_joy_db
      MYSQL_USER: petjoy_user
      MYSQL_PASSWORD: Parola123!
      MYSQL_ROOT_PASSWORD: Root123!
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./server
    container_name: petjoy_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pet_joy_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: petjoy_user
      SPRING_DATASOURCE_PASSWORD: Parola123!
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./client
    container_name: petjoy_frontend
    ports:
      - "5500:80"

volumes:
  db_data:
